### PR TITLE
avoiding out of index exception Fixes #294

### LINKED ISSUE #294: Index out of bounds exception when getting results
This exception occurs when trying to view results on the "Low Flow" scenario in the cache creek study.
image

The exception occurs here:
image

### PR DESCRIPTION
**Pull request by rnugent3**
small change in threadsafe inline histogram

### CODE REVIEW

**Comment by rnugent3** [comment]
It just occurred to me that revising the index could bias the frequency upward. If we think about the max as the upper bin limit which is excluded from a given bin (so bin min <= x < bin max) then the bin max would be included in the next bin, which has a frequency of zero. So maybe we return zero instead of changing the index?

File: Statistics/Histograms/ThreadsafeInlineHistogram.cs [hunk 1]
```diff
@@ -461,6 +461,10 @@ public void AddObservationsToHistogram(double[] data)
         public int FindBinCount(double x, bool cumulative = true)
         {
             int obsIndex = Convert.ToInt32(Math.Floor((x - _Min) / _BinWidth));
+            if (obsIndex == _BinCounts.Length)
```
Comment (HenryGeorgist) [inline Statistics/Histograms/ThreadsafeInlineHistogram.cs:464]: im a bit surprised here, floor should do that operation, but i assume you hit a bug, so this makes sense.

**Review by HenryGeorgist — APPROVED** [review]
looks good.

File: Statistics/Histograms/Histogram.cs [hunk 2]
```diff
@@ -345,6 +345,21 @@ public void AddObservationsToHistogram(double[] data)
         }
         public int FindBinCount(double x, bool cumulative = true)
```
Comment (HenryGeorgist) [inline Statistics/Histograms/Histogram.cs:346]: i guess the only reason we have findbincount as being public is because it is in the histogram interface (which seems unnecessary) it seems like this method should be private

**Review by HenryGeorgist — APPROVED** [review]
